# Get build image
FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build-stage
WORKDIR /app

# Copy source
COPY . ./

# Run tests if they are present
RUN bash run-tests.bash test/Promenade

# Publish
RUN dotnet publish -c Release -o "/app/publish/promenade" "src/Promenade.Web"

# Get runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 as publish-stage
WORKDIR /app

# Bring in metadata via --build-arg
ARG BRANCH=unknown
ARG IMAGE_CREATED=unknown
ARG IMAGE_REVISION=unknown
ARG IMAGE_VERSION=unknown

# Configure image labels
LABEL branch=$branch \
    maintainer="Maricopa County Library District developers <development@mcldaz.org>" \
    org.opencontainers.image.authors="Maricopa County Library District developers <development@mcldaz.org>" \
    org.opencontainers.image.created=$IMAGE_CREATED \
    org.opencontainers.image.description="Ocuda Promenade content management for libraries" \
    org.opencontainers.image.documentation="https://github.com/MCLD/ocuda" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.revision=$IMAGE_REVISION \
    org.opencontainers.image.source="https://github.com/MCLD/ocuda" \
    org.opencontainers.image.title="Ocuda Promenade" \
    org.opencontainers.image.url="https://github.com/MCLD/ocuda" \
    org.opencontainers.image.vendor="Maricopa County Library District" \
    org.opencontainers.image.version=$IMAGE_VERSION

# Default image environment variable settings
ENV org.opencontainers.image.created=$IMAGE_CREATED \
    org.opencontainers.image.revision=$IMAGE_REVISION \
    org.opencontainers.image.version=$IMAGE_VERSION

# Copy source
COPY --from=build-stage "/app/publish/ops" .

# Persist shared directory
VOLUME ["/app/shared"]

# Port 80 for http
EXPOSE 80

# Set entrypoint
ENTRYPOINT ["dotnet", "Ocuda.Promenade.Web.dll"]
