# Get build image
FROM mcr.microsoft.com/dotnet/sdk:6.0@sha256:e86848d2834af9afb04eb9f822344178b5aad3b1909a3325be71fb3e98c46be7 AS build

WORKDIR /app

# Copy source
COPY . ./

# Restore packages
RUN dotnet restore

# Build project and run tests
RUN dotnet test

# Publish
RUN dotnet publish -c Release -o "/app/publish/ops" "src/Ops.Web"

# Get runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0@sha256:353800b87bab585bdc7853a6357ca0c858c2052dfda87b6f85997a68f045e736 as publish

WORKDIR /app

# Install curl for health monitoring
RUN apt-get update \
	&& apt-get install --no-install-recommends -y curl=7.74.0-1.3+deb11u3 \
	&& rm -rf /var/lib/apt/lists/*

# Bring in metadata via --build-arg
ARG BRANCH=unknown
ARG IMAGE_CREATED=unknown
ARG IMAGE_REVISION=unknown
ARG IMAGE_VERSION=unknown

# Configure image labels
LABEL branch=$branch \
    maintainer="Maricopa County Library District developers <development@mcldaz.org>" \
    org.opencontainers.image.authors="Maricopa County Library District developers <development@mcldaz.org>" \
    org.opencontainers.image.created=$IMAGE_CREATED \
    org.opencontainers.image.description="Ocuda Ops content management for libraries" \
    org.opencontainers.image.documentation="https://github.com/MCLD/ocuda" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.revision=$IMAGE_REVISION \
    org.opencontainers.image.source="https://github.com/MCLD/ocuda" \
    org.opencontainers.image.title="Ocuda Ops" \
    org.opencontainers.image.url="https://github.com/MCLD/ocuda" \
    org.opencontainers.image.vendor="Maricopa County Library District" \
    org.opencontainers.image.version=$IMAGE_VERSION

# Default image environment variable settings
ENV org.opencontainers.image.created=$IMAGE_CREATED \
    org.opencontainers.image.revision=$IMAGE_REVISION \
    org.opencontainers.image.version=$IMAGE_VERSION

# Copy source
COPY --from=build "/app/publish/ops" .

# Persist shared directory
VOLUME ["/app/shared"]

# Port 80 for http
EXPOSE 80

# Configure health check
HEALTHCHECK CMD curl --fail http://localhost/health/ || exit

# Set entrypoint
ENTRYPOINT ["dotnet", "Ocuda.Ops.Web.dll"]
