# Get build image
FROM mcr.microsoft.com/dotnet/sdk:6.0@sha256:b48b7c00643738c5988aba448369c7f8840a55eaf6a9df925d8b93c9a1c0291a AS build

WORKDIR /app

# Copy source
COPY . ./

# Run tests if they are present
RUN dotnet restore

# Build project and run tests
RUN dotnet test

# Publish
RUN dotnet publish -c Release -o "/app/publish/promenade" "src/Promenade.Web"

# Get runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0@sha256:d8b274c1ac356a3bbea84204d20e99046ce5eae20cfa7fbcf703e5aa034cb36b as publish

WORKDIR /app

# Install curl for health monitoring
RUN apt-get update \
	&& apt-get install --no-install-recommends -y curl=7.74.0-1.3+deb11u1 \
	&& rm -rf /var/lib/apt/lists/*

# Bring in metadata via --build-arg
ARG BRANCH=unknown
ARG IMAGE_CREATED=unknown
ARG IMAGE_REVISION=unknown
ARG IMAGE_VERSION=unknown

# Configure image labels
LABEL branch=$branch \
    maintainer="Maricopa County Library District developers <development@mcldaz.org>" \
    org.opencontainers.image.authors="Maricopa County Library District developers <development@mcldaz.org>" \
    org.opencontainers.image.created=$IMAGE_CREATED \
    org.opencontainers.image.description="Ocuda Promenade content management for libraries" \
    org.opencontainers.image.documentation="https://github.com/MCLD/ocuda" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.revision=$IMAGE_REVISION \
    org.opencontainers.image.source="https://github.com/MCLD/ocuda" \
    org.opencontainers.image.title="Ocuda Promenade" \
    org.opencontainers.image.url="https://github.com/MCLD/ocuda" \
    org.opencontainers.image.vendor="Maricopa County Library District" \
    org.opencontainers.image.version=$IMAGE_VERSION

# Default image environment variable settings
ENV org.opencontainers.image.created=$IMAGE_CREATED \
    org.opencontainers.image.revision=$IMAGE_REVISION \
    org.opencontainers.image.version=$IMAGE_VERSION

# Copy source
COPY --from=build "/app/publish/promenade" .

# Persist shared directory
VOLUME ["/app/shared"]

# Port 80 for http
EXPOSE 80

# Configure health check
HEALTHCHECK CMD curl --fail http://localhost/health/ || exit

# Set entrypoint
ENTRYPOINT ["dotnet", "Ocuda.Promenade.Web.dll"]
