<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Ocuda.Ops.Controllers</AssemblyName>
    <Authors>Maricopa County Library District Web developers</Authors>
    <Company>Maricopa County Library District</Company>
    <Copyright>Copyright 2018 Maricopa County Library District</Copyright>
    <LangVersion>Latest</LangVersion>
    <PackageId>Ocuda.Ops.Controllers</PackageId>
    <PackageLicenseUrl>https://github.com/MCLD/ocuda/blob/develop/LICENSE</PackageLicenseUrl>
    <Product>Ocuda</Product>
    <RepositoryType>Git</RepositoryType>
    <RepositoryUrl>https://github.com/MCLD/ocuda/</RepositoryUrl>
    <RootNamespace>Ocuda.Ops.Controllers</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommonMark.NET" Version="0.15.1" />
    <PackageReference Include="NUglify" Version="1.22.3" />
    <PackageReference Include="Roslynator.Analyzers" Version="4.15.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="4.15.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Formatting.Analyzers" Version="4.15.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ocuda\MaricopaCountyAssessorHelper\MaricopaCountyAssessorHelper.csproj" />
    <ProjectReference Include="..\Ocuda\Models\Models.csproj" />
    <ProjectReference Include="..\Ops.Service\Ops.Service.csproj" />
    <ProjectReference Include="..\Ocuda\PolarisHelper\PolarisHelper.csproj" />
    <ProjectReference Include="..\Ocuda\TrestleHelper\TrestleHelper.csproj" />
    <ProjectReference Include="..\Ocuda\Utility\Utility.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ViewModels\Shared\" />
  </ItemGroup>

</Project>
