// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ocuda.Ops.DataProvider.SqlServer.Promenade;

#nullable disable

namespace Ocuda.Ops.DataProvider.SqlServer.Promenade.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.CardDetail", b =>
                {
                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("AltText")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Filename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Header")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("CardDetails");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Carousel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Carousels");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.CarouselButton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarouselItemId")
                        .HasColumnType("int");

                    b.Property<int>("LabelId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CarouselItemId");

                    b.HasIndex("LabelId");

                    b.ToTable("CarouselButtons");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.CarouselButtonLabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CarouselButtonLabels");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.CarouselButtonLabelText", b =>
                {
                    b.Property<int>("CarouselButtonLabelId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("CarouselButtonLabelId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("CarouselButtonLabelTexts");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.CarouselItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarouselId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarouselId");

                    b.ToTable("CarouselItems");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.CarouselItemText", b =>
                {
                    b.Property<int>("CarouselItemId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CarouselItemId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("CarouselItemTexts");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.CarouselTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonUrlInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ButtonUrlLabel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ButtonUrlTemplate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("CarouselTemplates");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.CarouselText", b =>
                {
                    b.Property<int>("CarouselId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CarouselId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("CarouselTexts");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.CategoryText", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("CategoryTexts");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Emedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RedirectUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Emedia");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.EmediaCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("EmediaId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "EmediaId");

                    b.HasIndex("EmediaId");

                    b.ToTable("EmediaCategories");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.EmediaGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SegmentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SegmentId");

                    b.ToTable("EmediaGroups");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.EmediaText", b =>
                {
                    b.Property<int>("EmediaId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("EmediaId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("EmediaTexts");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.ExternalResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ExternalResources");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyText")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("IconText")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Stub")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GroupType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsLocationRegion")
                        .HasColumnType("bit");

                    b.Property<string>("MapImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Stub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SubscriptionUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.ImageFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ImageFeatures");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.ImageFeatureItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImageFeatureId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ImageFeatureId");

                    b.ToTable("ImageFeatureItems");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.ImageFeatureItemText", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("ImageFeatureItemId")
                        .HasColumnType("int");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Filename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LanguageId", "ImageFeatureItemId");

                    b.HasIndex("ImageFeatureItemId");

                    b.ToTable("ImageFeatureItemTexts");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.ImageFeatureTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<int?>("ItemsToDisplay")
                        .HasColumnType("int");

                    b.Property<int?>("MaximumFileSizeBytes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ImageFeatureTemplates");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AddressType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AdministrativeArea")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AreaServedName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AreaServedType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ContactType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DescriptionSegmentId")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EventLink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Facebook")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GeoLocation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("HasEvents")
                        .HasColumnType("bit");

                    b.Property<int?>("HoursSegmentId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAccessibleForFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAlwaysOpen")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LocatorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LocatorNotes")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MapImagePath")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MapLink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PAbbreviation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ParentOrganization")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("PostFeatureSegmentId")
                        .HasColumnType("int");

                    b.Property<int?>("PreFeatureSegmentId")
                        .HasColumnType("int");

                    b.Property<string>("PriceRange")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SocialCardId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Stub")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SubscriptionLink")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Zip")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayGroupId");

                    b.HasIndex("SocialCardId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.LocationFeature", b =>
                {
                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<bool>("NewTab")
                        .HasColumnType("bit");

                    b.Property<string>("RedirectUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeatureId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("LocationFeatures");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.LocationForm", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.HasKey("LocationId", "FormId");

                    b.HasIndex("FormId");

                    b.ToTable("LocationForms");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.LocationGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("HasSubscription")
                        .HasColumnType("bit");

                    b.HasKey("GroupId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("LocationGroups");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.LocationHours", b =>
                {
                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Open")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OpenTime")
                        .HasColumnType("datetime2");

                    b.HasKey("DayOfWeek", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("LocationHours");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.LocationHoursOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<bool>("Open")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("LocationHoursOverrides");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.LocationProductMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImportLocation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.ToTable("LocationProductMaps");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Navigation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ChangeToLinkWhenExtraSmall")
                        .HasColumnType("bit");

                    b.Property<bool>("HideTextWhenExtraSmall")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("NavigationId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<bool>("TargetNewWindow")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NavigationId");

                    b.ToTable("Navigations");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.NavigationText", b =>
                {
                    b.Property<int>("NavigationId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("NavigationId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("NavigationTexts");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Page", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("PageHeaderId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int?>("SocialCardId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LanguageId", "PageHeaderId");

                    b.HasIndex("PageHeaderId");

                    b.HasIndex("SocialCardId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.PageHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLayoutPage")
                        .HasColumnType("bit");

                    b.Property<int?>("LayoutBannerTemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("LayoutCarouselTemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("LayoutFeatureTemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("LayoutWebslideTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Stub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LayoutBannerTemplateId");

                    b.HasIndex("LayoutCarouselTemplateId");

                    b.HasIndex("LayoutFeatureTemplateId");

                    b.HasIndex("LayoutWebslideTemplateId");

                    b.ToTable("PageHeaders");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.PageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BannerFeatureId")
                        .HasColumnType("int");

                    b.Property<int?>("CarouselId")
                        .HasColumnType("int");

                    b.Property<int?>("DeckId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("PageFeatureId")
                        .HasColumnType("int");

                    b.Property<int>("PageLayoutId")
                        .HasColumnType("int");

                    b.Property<int?>("SegmentId")
                        .HasColumnType("int");

                    b.Property<int?>("WebslideId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BannerFeatureId");

                    b.HasIndex("CarouselId");

                    b.HasIndex("DeckId");

                    b.HasIndex("PageFeatureId");

                    b.HasIndex("PageLayoutId");

                    b.HasIndex("SegmentId");

                    b.HasIndex("WebslideId");

                    b.ToTable("PageItems");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.PageLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PageHeaderId")
                        .HasColumnType("int");

                    b.Property<Guid>("PreviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SocialCardId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PageHeaderId");

                    b.HasIndex("SocialCardId");

                    b.ToTable("PageLayouts");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.PageLayoutText", b =>
                {
                    b.Property<int>("PageLayoutId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsTitleHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PageLayoutId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("PageLayoutTexts");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Podcast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Copyright")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExplicit")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSerial")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Stub")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Podcasts");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.PodcastDirectory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("PodcastDirectories");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.PodcastDirectoryInfo", b =>
                {
                    b.Property<int>("PodcastId")
                        .HasColumnType("int");

                    b.Property<int>("PodcastDirectoryId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PodcastId", "PodcastDirectoryId");

                    b.HasIndex("PodcastDirectoryId");

                    b.ToTable("PodcastDirectoryInfos");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.PodcastItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("Episode")
                        .HasColumnType("int");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("GuidPermaLink")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExplicit")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MediaSize")
                        .HasColumnType("int");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PodcastId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Season")
                        .HasColumnType("int");

                    b.Property<int?>("ShowNotesSegmentId")
                        .HasColumnType("int");

                    b.Property<string>("Stub")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PodcastId");

                    b.ToTable("PodcastItems");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CacheInventoryMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisibleToPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SegmentId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.ProductLocationInventory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("ItemCount")
                        .HasColumnType("int");

                    b.Property<int>("ManyThreshhold")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThreshholdUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ThreshholdUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("ProductLocationInventories");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.ScheduleRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancellationSentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FollowupSentAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClaimed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnderway")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NotificationSentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScheduleRequestSubjectId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleRequestTelephoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleRequestSubjectId");

                    b.HasIndex("ScheduleRequestTelephoneId");

                    b.ToTable("ScheduleRequest");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.ScheduleRequestLimit", b =>
                {
                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<int>("Limit")
                        .HasColumnType("int");

                    b.HasKey("DayOfWeek", "Hour");

                    b.ToTable("ScheduleRequestLimits");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.ScheduleRequestSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CancellationEmailSetupId")
                        .HasColumnType("int");

                    b.Property<int?>("FollowupEmailSetupId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedEmailSetupId")
                        .HasColumnType("int");

                    b.Property<bool>("RequireComments")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireEmail")
                        .HasColumnType("bit");

                    b.Property<int?>("SegmentId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ScheduleRequestSubject");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.ScheduleRequestSubjectText", b =>
                {
                    b.Property<int>("ScheduleRequestSubjectId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ScheduleRequestSubjectId", "LanguageId");

                    b.ToTable("ScheduleRequestSubjectTexts");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.ScheduleRequestTelephone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ScheduleRequestTelephone");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Segment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SegmentWrapId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SegmentWrapId");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.SegmentText", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("SegmentId")
                        .HasColumnType("int");

                    b.Property<string>("Header")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId", "SegmentId");

                    b.HasIndex("SegmentId");

                    b.ToTable("SegmentTexts");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.SegmentWrap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Prefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suffix")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SegmentWrap");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.SiteSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.SocialCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageAlt")
                        .HasMaxLength(420)
                        .HasColumnType("nvarchar(420)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("SocialCards");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.UrlRedirect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPermanent")
                        .HasColumnType("bit");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("UrlRedirects");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.UrlRedirectAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccessDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrlRedirectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UrlRedirectId");

                    b.ToTable("UrlRedirectAccesses");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.VolunteerForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HeaderSegmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<int?>("NotifyStaffEmailSetupId")
                        .HasColumnType("int");

                    b.Property<int?>("ThanksPageHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("VolunteerFormType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThanksPageHeaderId");

                    b.ToTable("VolunteerForms");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.VolunteerFormSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Availability")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Experience")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GuardianEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GuardianName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GuardianPhone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Regularity")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("StaffNotifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VolunteerFormId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VolunteerFormId");

                    b.ToTable("VolunteerFormSubmissions");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Card", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.CardDetail", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.CarouselButton", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.CarouselItem", "CarouselItem")
                        .WithMany("Buttons")
                        .HasForeignKey("CarouselItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.CarouselButtonLabel", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarouselItem");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.CarouselButtonLabelText", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.CarouselButtonLabel", "CarouselButtonLabel")
                        .WithMany()
                        .HasForeignKey("CarouselButtonLabelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarouselButtonLabel");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.CarouselItem", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Carousel", "Carousel")
                        .WithMany("Items")
                        .HasForeignKey("CarouselId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carousel");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.CarouselItemText", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.CarouselItem", "CarouselItem")
                        .WithMany()
                        .HasForeignKey("CarouselItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarouselItem");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.CarouselText", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Carousel", "Carousel")
                        .WithMany()
                        .HasForeignKey("CarouselId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carousel");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.CategoryText", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Emedia", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.EmediaGroup", "Group")
                        .WithMany("Emedias")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.EmediaCategory", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.Emedia", "Emedia")
                        .WithMany()
                        .HasForeignKey("EmediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Emedia");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.EmediaGroup", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Segment", "Segment")
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.EmediaText", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Emedia", "Emedia")
                        .WithMany()
                        .HasForeignKey("EmediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emedia");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.ImageFeatureItem", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.ImageFeature", "ImageFeature")
                        .WithMany("Items")
                        .HasForeignKey("ImageFeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImageFeature");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.ImageFeatureItemText", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.ImageFeatureItem", "ImageFeatureItem")
                        .WithMany()
                        .HasForeignKey("ImageFeatureItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImageFeatureItem");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Location", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Group", "DisplayGroup")
                        .WithMany()
                        .HasForeignKey("DisplayGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ocuda.Promenade.Models.Entities.SocialCard", "SocialCard")
                        .WithMany()
                        .HasForeignKey("SocialCardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DisplayGroup");

                    b.Navigation("SocialCard");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.LocationFeature", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.LocationForm", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.VolunteerForm", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.LocationGroup", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.LocationHours", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.LocationHoursOverride", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.LocationProductMap", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Navigation", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Navigation", null)
                        .WithMany("Navigations")
                        .HasForeignKey("NavigationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.NavigationText", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.Navigation", "Navigation")
                        .WithMany()
                        .HasForeignKey("NavigationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Navigation");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Page", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.PageHeader", "PageHeader")
                        .WithMany()
                        .HasForeignKey("PageHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.SocialCard", "SocialCard")
                        .WithMany()
                        .HasForeignKey("SocialCardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Language");

                    b.Navigation("PageHeader");

                    b.Navigation("SocialCard");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.PageHeader", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.ImageFeatureTemplate", "LayoutBannerTemplate")
                        .WithMany()
                        .HasForeignKey("LayoutBannerTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ocuda.Promenade.Models.Entities.CarouselTemplate", "LayoutCarouselTemplate")
                        .WithMany()
                        .HasForeignKey("LayoutCarouselTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ocuda.Promenade.Models.Entities.ImageFeatureTemplate", "LayoutFeatureTemplate")
                        .WithMany()
                        .HasForeignKey("LayoutFeatureTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ocuda.Promenade.Models.Entities.ImageFeatureTemplate", "LayoutWebslideTemplate")
                        .WithMany()
                        .HasForeignKey("LayoutWebslideTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LayoutBannerTemplate");

                    b.Navigation("LayoutCarouselTemplate");

                    b.Navigation("LayoutFeatureTemplate");

                    b.Navigation("LayoutWebslideTemplate");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.PageItem", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.ImageFeature", "BannerFeature")
                        .WithMany()
                        .HasForeignKey("BannerFeatureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ocuda.Promenade.Models.Entities.Carousel", "Carousel")
                        .WithMany()
                        .HasForeignKey("CarouselId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ocuda.Promenade.Models.Entities.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ocuda.Promenade.Models.Entities.ImageFeature", "PageFeature")
                        .WithMany()
                        .HasForeignKey("PageFeatureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ocuda.Promenade.Models.Entities.PageLayout", "PageLayout")
                        .WithMany("Items")
                        .HasForeignKey("PageLayoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.Segment", "Segment")
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ocuda.Promenade.Models.Entities.ImageFeature", "Webslide")
                        .WithMany()
                        .HasForeignKey("WebslideId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BannerFeature");

                    b.Navigation("Carousel");

                    b.Navigation("Deck");

                    b.Navigation("PageFeature");

                    b.Navigation("PageLayout");

                    b.Navigation("Segment");

                    b.Navigation("Webslide");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.PageLayout", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.PageHeader", "PageHeader")
                        .WithMany()
                        .HasForeignKey("PageHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.SocialCard", "SocialCard")
                        .WithMany()
                        .HasForeignKey("SocialCardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PageHeader");

                    b.Navigation("SocialCard");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.PageLayoutText", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.PageLayout", "PageLayout")
                        .WithMany()
                        .HasForeignKey("PageLayoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("PageLayout");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.PodcastDirectoryInfo", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.PodcastDirectory", "PodcastDirectory")
                        .WithMany()
                        .HasForeignKey("PodcastDirectoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.Podcast", "Podcast")
                        .WithMany()
                        .HasForeignKey("PodcastId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Podcast");

                    b.Navigation("PodcastDirectory");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.PodcastItem", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Podcast", "Podcast")
                        .WithMany("PodcastItems")
                        .HasForeignKey("PodcastId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Podcast");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.ProductLocationInventory", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.ScheduleRequest", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.ScheduleRequestSubject", "ScheduleRequestSubject")
                        .WithMany()
                        .HasForeignKey("ScheduleRequestSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.ScheduleRequestTelephone", "ScheduleRequestTelephone")
                        .WithMany()
                        .HasForeignKey("ScheduleRequestTelephoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScheduleRequestSubject");

                    b.Navigation("ScheduleRequestTelephone");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Segment", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.SegmentWrap", "SegmentWrap")
                        .WithMany()
                        .HasForeignKey("SegmentWrapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SegmentWrap");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.SegmentText", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ocuda.Promenade.Models.Entities.Segment", "Segment")
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.UrlRedirectAccess", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.UrlRedirect", "UrlRedirect")
                        .WithMany()
                        .HasForeignKey("UrlRedirectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UrlRedirect");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.VolunteerForm", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.PageHeader", "ThanksPageHeader")
                        .WithMany()
                        .HasForeignKey("ThanksPageHeaderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ThanksPageHeader");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.VolunteerFormSubmission", b =>
                {
                    b.HasOne("Ocuda.Promenade.Models.Entities.VolunteerForm", "VolunteerForm")
                        .WithMany("VolunteerFormSubmissions")
                        .HasForeignKey("VolunteerFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VolunteerForm");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Carousel", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.CarouselItem", b =>
                {
                    b.Navigation("Buttons");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Deck", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.EmediaGroup", b =>
                {
                    b.Navigation("Emedias");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.ImageFeature", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Navigation", b =>
                {
                    b.Navigation("Navigations");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.PageLayout", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.Podcast", b =>
                {
                    b.Navigation("PodcastItems");
                });

            modelBuilder.Entity("Ocuda.Promenade.Models.Entities.VolunteerForm", b =>
                {
                    b.Navigation("VolunteerFormSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
